In [1]:
import numpy as np
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split

In [2]:
import pandas as pd
pd.set_option('display.max_rows', None)

In [3]:
help(fetch_openml)

Help on function fetch_openml in module sklearn.datasets._openml:

fetch_openml(name: Optional[str] = None, *, version: Union[str, int] = 'active', data_id: Optional[int] = None, data_home: Union[str, os.PathLike, NoneType] = None, target_column: Union[str, List, NoneType] = 'default-target', cache: bool = True, return_X_y: bool = False, as_frame: Union[str, bool] = 'auto', n_retries: int = 3, delay: float = 1.0, parser: str = 'auto', read_csv_kwargs: Optional[Dict] = None)
    Fetch dataset from openml by name or dataset id.

    Datasets are uniquely identified by either an integer ID or by a
    combination of name and version (i.e. there might be multiple
    versions of the 'iris' dataset). Please give either name or data_id
    (not both). In case a name is given, a version can also be
    provided.

    Read more in the :ref:`User Guide <openml>`.

    .. versionadded:: 0.20

    .. note:: EXPERIMENTAL

        The API is experimental (particularly the return value structure),
        and might have small backward-incompatible changes without notice
        or warning in future releases.

    Parameters
    ----------
    name : str, default=None
        String identifier of the dataset. Note that OpenML can have multiple
        datasets with the same name.

    version : int or 'active', default='active'
        Version of the dataset. Can only be provided if also ``name`` is given.
        If 'active' the oldest version that's still active is used. Since
        there may be more than one active version of a dataset, and those
        versions may fundamentally be different from one another, setting an
        exact version is highly recommended.

    data_id : int, default=None
        OpenML ID of the dataset. The most specific way of retrieving a
        dataset. If data_id is not given, name (and potential version) are
        used to obtain a dataset.

    data_home : str or path-like, default=None
        Specify another download and cache folder for the data sets. By default
        all scikit-learn data is stored in '~/scikit_learn_data' subfolders.

    target_column : str, list or None, default='default-target'
        Specify the column name in the data to use as target. If
        'default-target', the standard target column a stored on the server
        is used. If ``None``, all columns are returned as data and the
        target is ``None``. If list (of strings), all columns with these names
        are returned as multi-target (Note: not all scikit-learn classifiers
        can handle all types of multi-output combinations).

    cache : bool, default=True
        Whether to cache the downloaded datasets into `data_home`.

    return_X_y : bool, default=False
        If True, returns ``(data, target)`` instead of a Bunch object. See
        below for more information about the `data` and `target` objects.

    as_frame : bool or 'auto', default='auto'
        If True, the data is a pandas DataFrame including columns with
        appropriate dtypes (numeric, string or categorical). The target is
        a pandas DataFrame or Series depending on the number of target_columns.
        The Bunch will contain a ``frame`` attribute with the target and the
        data. If ``return_X_y`` is True, then ``(data, target)`` will be pandas
        DataFrames or Series as describe above.

        If `as_frame` is 'auto', the data and target will be converted to
        DataFrame or Series as if `as_frame` is set to True, unless the dataset
        is stored in sparse format.

        If `as_frame` is False, the data and target will be NumPy arrays and
        the `data` will only contain numerical values when `parser="liac-arff"`
        where the categories are provided in the attribute `categories` of the
        `Bunch` instance. When `parser="pandas"`, no ordinal encoding is made.

        .. versionchanged:: 0.24
           The default value of `as_frame` changed from `False` to `'auto'`
           in 0.24.

    n_retries : int, default=3
        Number of retries when HTTP errors or network timeouts are encountered.
        Error with status code 412 won't be retried as they represent OpenML
        generic errors.

    delay : float, default=1.0
        Number of seconds between retries.

    parser : {"auto", "pandas", "liac-arff"}, default="auto"
        Parser used to load the ARFF file. Two parsers are implemented:

        - `"pandas"`: this is the most efficient parser. However, it requires
          pandas to be installed and can only open dense datasets.
        - `"liac-arff"`: this is a pure Python ARFF parser that is much less
          memory- and CPU-efficient. It deals with sparse ARFF datasets.

        If `"auto"`, the parser is chosen automatically such that `"liac-arff"`
        is selected for sparse ARFF datasets, otherwise `"pandas"` is selected.

        .. versionadded:: 1.2
        .. versionchanged:: 1.4
           The default value of `parser` changes from `"liac-arff"` to
           `"auto"`.

    read_csv_kwargs : dict, default=None
        Keyword arguments passed to :func:`pandas.read_csv` when loading the data
        from a ARFF file and using the pandas parser. It can allow to
        overwrite some default parameters.

        .. versionadded:: 1.3

    Returns
    -------
    data : :class:`~sklearn.utils.Bunch`
        Dictionary-like object, with the following attributes.

        data : np.array, scipy.sparse.csr_matrix of floats, or pandas DataFrame
            The feature matrix. Categorical features are encoded as ordinals.
        target : np.array, pandas Series or DataFrame
            The regression target or classification labels, if applicable.
            Dtype is float if numeric, and object if categorical. If
            ``as_frame`` is True, ``target`` is a pandas object.
        DESCR : str
            The full description of the dataset.
        feature_names : list
            The names of the dataset columns.
        target_names: list
            The names of the target columns.

        .. versionadded:: 0.22

        categories : dict or None
            Maps each categorical feature name to a list of values, such
            that the value encoded as i is ith in the list. If ``as_frame``
            is True, this is None.
        details : dict
            More metadata from OpenML.
        frame : pandas DataFrame
            Only present when `as_frame=True`. DataFrame with ``data`` and
            ``target``.

    (data, target) : tuple if ``return_X_y`` is True

        .. note:: EXPERIMENTAL

            This interface is **experimental** and subsequent releases may
            change attributes without notice (although there should only be
            minor changes to ``data`` and ``target``).

        Missing values in the 'data' are represented as NaN's. Missing values
        in 'target' are represented as NaN's (numerical target) or None
        (categorical target).

    Notes
    -----
    The `"pandas"` and `"liac-arff"` parsers can lead to different data types
    in the output. The notable differences are the following:

    - The `"liac-arff"` parser always encodes categorical features as `str` objects.
      To the contrary, the `"pandas"` parser instead infers the type while
      reading and numerical categories will be casted into integers whenever
      possible.
    - The `"liac-arff"` parser uses float64 to encode numerical features
      tagged as 'REAL' and 'NUMERICAL' in the metadata. The `"pandas"`
      parser instead infers if these numerical features corresponds
      to integers and uses panda's Integer extension dtype.
    - In particular, classification datasets with integer categories are
      typically loaded as such `(0, 1, ...)` with the `"pandas"` parser while
      `"liac-arff"` will force the use of string encoded class labels such as
      `"0"`, `"1"` and so on.
    - The `"pandas"` parser will not strip single quotes - i.e. `'` - from
      string columns. For instance, a string `'my string'` will be kept as is
      while the `"liac-arff"` parser will strip the single quotes. For
      categorical columns, the single quotes are stripped from the values.

    In addition, when `as_frame=False` is used, the `"liac-arff"` parser
    returns ordinally encoded data where the categories are provided in the
    attribute `categories` of the `Bunch` instance. Instead, `"pandas"` returns
    a NumPy array were the categories are not encoded.

    Examples
    --------
    >>> from sklearn.datasets import fetch_openml
    >>> adult = fetch_openml("adult", version=2)  # doctest: +SKIP
    >>> adult.frame.info()  # doctest: +SKIP
    <class 'pandas.core.frame.DataFrame'>
    RangeIndex: 48842 entries, 0 to 48841
    Data columns (total 15 columns):
     #   Column          Non-Null Count  Dtype
    ---  ------          --------------  -----
     0   age             48842 non-null  int64
     1   workclass       46043 non-null  category
     2   fnlwgt          48842 non-null  int64
     3   education       48842 non-null  category
     4   education-num   48842 non-null  int64
     5   marital-status  48842 non-null  category
     6   occupation      46033 non-null  category
     7   relationship    48842 non-null  category
     8   race            48842 non-null  category
     9   sex             48842 non-null  category
     10  capital-gain    48842 non-null  int64
     11  capital-loss    48842 non-null  int64
     12  hours-per-week  48842 non-null  int64
     13  native-country  47985 non-null  category
     14  class           48842 non-null  category
    dtypes: category(9), int64(6)
    memory usage: 2.7 MB

In [4]:
mnist = fetch_openml('mnist_784', version=1)

In [5]:
mnist_images = mnist.data.astype('float32')/255.0

In [6]:
mnist_images.max()

pixel1      0.000000
pixel2      0.000000
pixel3      0.000000
pixel4      0.000000
pixel5      0.000000
pixel6      0.000000
pixel7      0.000000
pixel8      0.000000
pixel9      0.000000
pixel10     0.000000
pixel11     0.000000
pixel12     0.000000
pixel13     0.454902
pixel14     0.996078
pixel15     0.847059
pixel16     0.035294
pixel17     0.000000
pixel18     0.000000
pixel19     0.000000
pixel20     0.000000
pixel21     0.000000
pixel22     0.000000
pixel23     0.000000
pixel24     0.000000
pixel25     0.000000
pixel26     0.000000
pixel27     0.000000
pixel28     0.000000
pixel29     0.000000
pixel30     0.000000
pixel31     0.000000
pixel32     0.000000
pixel33     0.062745
pixel34     0.184314
pixel35     0.925490
pixel36     0.996078
pixel37     1.000000
pixel38     0.996078
pixel39     1.000000
pixel40     1.000000
pixel41     1.000000
pixel42     1.000000
pixel43     1.000000
pixel44     1.000000
pixel45     1.000000
pixel46     1.000000
pixel47     1.000000
pixel48     1.000000
pixel49     0.956863
pixel50     1.000000
pixel51     0.721569
pixel52     0.772549
pixel53     0.000000
pixel54     0.000000
pixel55     0.000000
pixel56     0.000000
pixel57     0.000000
pixel58     0.000000
pixel59     0.250980
pixel60     0.113725
pixel61     0.525490
pixel62     0.752941
pixel63     0.996078
pixel64     1.000000
pixel65     1.000000
pixel66     1.000000
pixel67     1.000000
pixel68     1.000000
pixel69     1.000000
pixel70     1.000000
pixel71     1.000000
pixel72     1.000000
pixel73     1.000000
pixel74     1.000000
pixel75     1.000000
pixel76     1.000000
pixel77     1.000000
pixel78     1.000000
pixel79     1.000000
pixel80     1.000000
pixel81     1.000000
pixel82     0.647059
pixel83     0.000000
pixel84     0.000000
pixel85     0.000000
pixel86     0.000000
pixel87     0.552941
pixel88     0.396078
pixel89     0.545098
pixel90     1.000000
pixel91     1.000000
pixel92     1.000000
pixel93     1.000000
pixel94     1.000000
pixel95     1.000000
pixel96     1.000000
pixel97     1.000000
pixel98     1.000000
pixel99     1.000000
pixel100    1.000000
pixel101    1.000000
pixel102    1.000000
pixel103    1.000000
pixel104    1.000000
pixel105    1.000000
pixel106    1.000000
pixel107    1.000000
pixel108    1.000000
pixel109    1.000000
pixel110    0.917647
pixel111    0.639216
pixel112    0.000000
pixel113    0.000000
pixel114    0.149020
pixel115    0.564706
pixel116    0.447059
pixel117    0.996078
pixel118    1.000000
pixel119    1.000000
pixel120    1.000000
pixel121    1.000000
pixel122    1.000000
pixel123    1.000000
pixel124    1.000000
pixel125    1.000000
pixel126    1.000000
pixel127    1.000000
pixel128    1.000000
pixel129    1.000000
pixel130    1.000000
pixel131    1.000000
pixel132    1.000000
pixel133    1.000000
pixel134    1.000000
pixel135    1.000000
pixel136    1.000000
pixel137    1.000000
pixel138    1.000000
pixel139    0.964706
pixel140    0.247059
pixel141    0.000000
pixel142    0.094118
pixel143    0.372549
pixel144    1.000000
pixel145    1.000000
pixel146    1.000000
pixel147    1.000000
pixel148    1.000000
pixel149    1.000000
pixel150    1.000000
pixel151    1.000000
pixel152    1.000000
pixel153    1.000000
pixel154    1.000000
pixel155    1.000000
pixel156    1.000000
pixel157    1.000000
pixel158    1.000000
pixel159    1.000000
pixel160    1.000000
pixel161    1.000000
pixel162    1.000000
pixel163    1.000000
pixel164    1.000000
pixel165    1.000000
pixel166    1.000000
pixel167    1.000000
pixel168    0.364706
pixel169    0.000000
pixel170    0.027451
pixel171    0.823529
pixel172    1.000000
pixel173    1.000000
pixel174    1.000000
pixel175    1.000000
pixel176    1.000000
pixel177    1.000000
pixel178    1.000000
pixel179    1.000000
pixel180    1.000000
pixel181    1.000000
pixel182    1.000000
pixel183    1.000000
pixel184    1.000000
pixel185    1.000000
pixel186    1.000000
pixel187    1.000000
pixel188    1.000000
pixel189    1.000000
pixel190    1.000000
pixel191    1.000000
pixel192    1.000000
pixel193    1.000000
pixel194    1.000000
pixel195    0.996078
pixel196    0.992157
pixel197    0.184314
pixel198    0.749020
pixel199    1.000000
pixel200    1.000000
pixel201    1.000000
pixel202    1.000000
pixel203    1.000000
pixel204    1.000000
pixel205    1.000000
pixel206    1.000000
pixel207    1.000000
pixel208    1.000000
pixel209    1.000000
pixel210    1.000000
pixel211    1.000000
pixel212    1.000000
pixel213    1.000000
pixel214    1.000000
pixel215    1.000000
pixel216    1.000000
pixel217    1.000000
pixel218    1.000000
pixel219    1.000000
pixel220    1.000000
pixel221    1.000000
pixel222    1.000000
pixel223    1.000000
pixel224    0.992157
pixel225    0.749020
pixel226    1.000000
pixel227    1.000000
pixel228    1.000000
pixel229    1.000000
pixel230    1.000000
pixel231    1.000000
pixel232    1.000000
pixel233    1.000000
pixel234    1.000000
pixel235    1.000000
pixel236    1.000000
pixel237    1.000000
pixel238    1.000000
pixel239    1.000000
pixel240    1.000000
pixel241    1.000000
pixel242    1.000000
pixel243    1.000000
pixel244    1.000000
pixel245    1.000000
pixel246    1.000000
pixel247    1.000000
pixel248    1.000000
pixel249    1.000000
pixel250    1.000000
pixel251    0.996078
pixel252    0.866667
pixel253    0.721569
pixel254    0.996078
pixel255    1.000000
pixel256    1.000000
pixel257    1.000000
pixel258    1.000000
pixel259    1.000000
pixel260    1.000000
pixel261    1.000000
pixel262    1.000000
pixel263    1.000000
pixel264    1.000000
pixel265    1.000000
pixel266    1.000000
pixel267    1.000000
pixel268    1.000000
pixel269    1.000000
pixel270    1.000000
pixel271    1.000000
pixel272    1.000000
pixel273    1.000000
pixel274    1.000000
pixel275    1.000000
pixel276    1.000000
pixel277    1.000000
pixel278    1.000000
pixel279    1.000000
pixel280    0.862745
pixel281    0.886275
pixel282    1.000000
pixel283    1.000000
pixel284    1.000000
pixel285    1.000000
pixel286    1.000000
pixel287    1.000000
pixel288    1.000000
pixel289    1.000000
pixel290    1.000000
pixel291    1.000000
pixel292    1.000000
pixel293    1.000000
pixel294    1.000000
pixel295    1.000000
pixel296    1.000000
pixel297    1.000000
pixel298    1.000000
pixel299    1.000000
pixel300    1.000000
pixel301    1.000000
pixel302    1.000000
pixel303    1.000000
pixel304    1.000000
pixel305    1.000000
pixel306    1.000000
pixel307    0.996078
pixel308    0.952941
pixel309    0.588235
pixel310    1.000000
pixel311    1.000000
pixel312    1.000000
pixel313    1.000000
pixel314    1.000000
pixel315    1.000000
pixel316    1.000000
pixel317    1.000000
pixel318    1.000000
pixel319    1.000000
pixel320    1.000000
pixel321    1.000000
pixel322    1.000000
pixel323    1.000000
pixel324    1.000000
pixel325    1.000000
pixel326    1.000000
pixel327    1.000000
pixel328    1.000000
pixel329    1.000000
pixel330    1.000000
pixel331    1.000000
pixel332    1.000000
pixel333    1.000000
pixel334    1.000000
pixel335    0.992157
pixel336    0.611765
pixel337    0.639216
pixel338    1.000000
pixel339    1.000000
pixel340    1.000000
pixel341    1.000000
pixel342    1.000000
pixel343    1.000000
pixel344    1.000000
pixel345    1.000000
pixel346    1.000000
pixel347    1.000000
pixel348    1.000000
pixel349    1.000000
pixel350    1.000000
pixel351    1.000000
pixel352    1.000000
pixel353    1.000000
pixel354    1.000000
pixel355    1.000000
pixel356    1.000000
pixel357    1.000000
pixel358    1.000000
pixel359    1.000000
pixel360    1.000000
pixel361    1.000000
pixel362    1.000000
pixel363    0.988235
pixel364    0.596078
pixel365    0.125490
pixel366    0.992157
pixel367    1.000000
pixel368    1.000000
pixel369    1.000000
pixel370    1.000000
pixel371    1.000000
pixel372    1.000000
pixel373    1.000000
pixel374    1.000000
pixel375    1.000000
pixel376    1.000000
pixel377    1.000000
pixel378    1.000000
pixel379    1.000000
pixel380    1.000000
pixel381    1.000000
pixel382    1.000000
pixel383    1.000000
pixel384    1.000000
pixel385    1.000000
pixel386    1.000000
pixel387    1.000000
pixel388    1.000000
pixel389    1.000000
pixel390    1.000000
pixel391    0.988235
pixel392    0.968627
pixel393    0.443137
pixel394    0.737255
pixel395    0.996078
pixel396    1.000000
pixel397    1.000000
pixel398    1.000000
pixel399    1.000000
pixel400    1.000000
pixel401    1.000000
pixel402    1.000000
pixel403    1.000000
pixel404    1.000000
pixel405    1.000000
pixel406    1.000000
pixel407    1.000000
pixel408    1.000000
pixel409    1.000000
pixel410    1.000000
pixel411    1.000000
pixel412    1.000000
pixel413    1.000000
pixel414    1.000000
pixel415    1.000000
pixel416    1.000000
pixel417    1.000000
pixel418    1.000000
pixel419    0.996078
pixel420    0.203922
pixel421    0.145098
pixel422    0.886275
pixel423    0.996078
pixel424    1.000000
pixel425    1.000000
pixel426    1.000000
pixel427    1.000000
pixel428    1.000000
pixel429    1.000000
pixel430    1.000000
pixel431    1.000000
pixel432    1.000000
pixel433    1.000000
pixel434    1.000000
pixel435    1.000000
pixel436    1.000000
pixel437    1.000000
pixel438    1.000000
pixel439    1.000000
pixel440    1.000000
pixel441    1.000000
pixel442    1.000000
pixel443    1.000000
pixel444    1.000000
pixel445    1.000000
pixel446    1.000000
pixel447    1.000000
pixel448    0.745098
pixel449    0.156863
pixel450    0.419608
pixel451    0.996078
pixel452    1.000000
pixel453    1.000000
pixel454    1.000000
pixel455    1.000000
pixel456    1.000000
pixel457    1.000000
pixel458    1.000000
pixel459    1.000000
pixel460    1.000000
pixel461    1.000000
pixel462    1.000000
pixel463    1.000000
pixel464    1.000000
pixel465    1.000000
pixel466    1.000000
pixel467    1.000000
pixel468    1.000000
pixel469    1.000000
pixel470    1.000000
pixel471    1.000000
pixel472    1.000000
pixel473    1.000000
pixel474    1.000000
pixel475    0.996078
pixel476    0.874510
pixel477    0.000000
pixel478    0.521569
pixel479    0.996078
pixel480    1.000000
pixel481    1.000000
pixel482    1.000000
pixel483    1.000000
pixel484    1.000000
pixel485    1.000000
pixel486    1.000000
pixel487    1.000000
pixel488    1.000000
pixel489    1.000000
pixel490    1.000000
pixel491    1.000000
pixel492    1.000000
pixel493    1.000000
pixel494    1.000000
pixel495    1.000000
pixel496    1.000000
pixel497    1.000000
pixel498    1.000000
pixel499    1.000000
pixel500    1.000000
pixel501    1.000000
pixel502    1.000000
pixel503    0.992157
pixel504    0.474510
pixel505    0.235294
pixel506    0.772549
pixel507    1.000000
pixel508    1.000000
pixel509    1.000000
pixel510    1.000000
pixel511    1.000000
pixel512    1.000000
pixel513    1.000000
pixel514    1.000000
pixel515    1.000000
pixel516    1.000000
pixel517    1.000000
pixel518    1.000000
pixel519    1.000000
pixel520    1.000000
pixel521    1.000000
pixel522    1.000000
pixel523    1.000000
pixel524    1.000000
pixel525    1.000000
pixel526    1.000000
pixel527    1.000000
pixel528    1.000000
pixel529    1.000000
pixel530    1.000000
pixel531    1.000000
pixel532    0.600000
pixel533    0.058824
pixel534    1.000000
pixel535    1.000000
pixel536    1.000000
pixel537    1.000000
pixel538    1.000000
pixel539    1.000000
pixel540    1.000000
pixel541    1.000000
pixel542    1.000000
pixel543    1.000000
pixel544    1.000000
pixel545    1.000000
pixel546    1.000000
pixel547    1.000000
pixel548    1.000000
pixel549    1.000000
pixel550    1.000000
pixel551    1.000000
pixel552    1.000000
pixel553    1.000000
pixel554    1.000000
pixel555    1.000000
pixel556    1.000000
pixel557    1.000000
pixel558    1.000000
pixel559    0.992157
pixel560    0.501961
pixel561    0.000000
pixel562    0.725490
pixel563    1.000000
pixel564    1.000000
pixel565    1.000000
pixel566    1.000000
pixel567    1.000000
pixel568    1.000000
pixel569    1.000000
pixel570    1.000000
pixel571    1.000000
pixel572    1.000000
pixel573    1.000000
pixel574    1.000000
pixel575    1.000000
pixel576    1.000000
pixel577    1.000000
pixel578    1.000000
pixel579    1.000000
pixel580    1.000000
pixel581    1.000000
pixel582    1.000000
pixel583    1.000000
pixel584    1.000000
pixel585    1.000000
pixel586    1.000000
pixel587    1.000000
pixel588    0.200000
pixel589    0.125490
pixel590    0.725490
pixel591    1.000000
pixel592    1.000000
pixel593    1.000000
pixel594    1.000000
pixel595    1.000000
pixel596    1.000000
pixel597    1.000000
pixel598    1.000000
pixel599    1.000000
pixel600    1.000000
pixel601    1.000000
pixel602    1.000000
pixel603    1.000000
pixel604    1.000000
pixel605    1.000000
pixel606    1.000000
pixel607    1.000000
pixel608    1.000000
pixel609    1.000000
pixel610    1.000000
pixel611    1.000000
pixel612    1.000000
pixel613    1.000000
pixel614    1.000000
pixel615    0.988235
pixel616    0.152941
pixel617    0.121569
pixel618    0.149020
pixel619    1.000000
pixel620    1.000000
pixel621    1.000000
pixel622    1.000000
pixel623    1.000000
pixel624    1.000000
pixel625    1.000000
pixel626    1.000000
pixel627    1.000000
pixel628    1.000000
pixel629    1.000000
pixel630    1.000000
pixel631    1.000000
pixel632    1.000000
pixel633    1.000000
pixel634    1.000000
pixel635    1.000000
pixel636    1.000000
pixel637    1.000000
pixel638    1.000000
pixel639    1.000000
pixel640    1.000000
pixel641    1.000000
pixel642    0.996078
pixel643    0.882353
pixel644    0.282353
pixel645    0.000000
pixel646    0.094118
pixel647    0.850980
pixel648    1.000000
pixel649    1.000000
pixel650    1.000000
pixel651    1.000000
pixel652    1.000000
pixel653    1.000000
pixel654    1.000000
pixel655    1.000000
pixel656    1.000000
pixel657    1.000000
pixel658    1.000000
pixel659    1.000000
pixel660    1.000000
pixel661    1.000000
pixel662    1.000000
pixel663    1.000000
pixel664    1.000000
pixel665    1.000000
pixel666    1.000000
pixel667    1.000000
pixel668    1.000000
pixel669    1.000000
pixel670    0.996078
pixel671    0.588235
pixel672    0.000000
pixel673    0.000000
pixel674    0.000000
pixel675    0.992157
pixel676    0.992157
pixel677    1.000000
pixel678    1.000000
pixel679    1.000000
pixel680    1.000000
pixel681    1.000000
pixel682    1.000000
pixel683    1.000000
pixel684    1.000000
pixel685    1.000000
pixel686    1.000000
pixel687    1.000000
pixel688    1.000000
pixel689    1.000000
pixel690    1.000000
pixel691    1.000000
pixel692    1.000000
pixel693    1.000000
pixel694    1.000000
pixel695    1.000000
pixel696    1.000000
pixel697    0.996078
pixel698    0.988235
pixel699    0.384314
pixel700    0.000000
pixel701    0.000000
pixel702    0.000000
pixel703    0.164706
pixel704    0.996078
pixel705    1.000000
pixel706    1.000000
pixel707    1.000000
pixel708    1.000000
pixel709    1.000000
pixel710    1.000000
pixel711    1.000000
pixel712    1.000000
pixel713    1.000000
pixel714    1.000000
pixel715    1.000000
pixel716    1.000000
pixel717    1.000000
pixel718    1.000000
pixel719    1.000000
pixel720    1.000000
pixel721    1.000000
pixel722    1.000000
pixel723    1.000000
pixel724    1.000000
pixel725    0.992157
pixel726    0.498039
pixel727    0.407843
pixel728    0.000000
pixel729    0.000000
pixel730    0.000000
pixel731    0.000000
pixel732    0.149020
pixel733    1.000000
pixel734    1.000000
pixel735    1.000000
pixel736    1.000000
pixel737    1.000000
pixel738    1.000000
pixel739    1.000000
pixel740    1.000000
pixel741    1.000000
pixel742    1.000000
pixel743    1.000000
pixel744    1.000000
pixel745    1.000000
pixel746    1.000000
pixel747    1.000000
pixel748    1.000000
pixel749    1.000000
pixel750    1.000000
pixel751    1.000000
pixel752    0.992157
pixel753    0.109804
pixel754    0.231373
pixel755    0.000000
pixel756    0.000000
pixel757    0.000000
pixel758    0.000000
pixel759    0.000000
pixel760    0.000000
pixel761    0.368627
pixel762    0.988235
pixel763    0.960784
pixel764    0.996078
pixel765    0.996078
pixel766    1.000000
pixel767    1.000000
pixel768    1.000000
pixel769    1.000000
pixel770    1.000000
pixel771    1.000000
pixel772    1.000000
pixel773    1.000000
pixel774    1.000000
pixel775    0.996078
pixel776    0.996078
pixel777    0.992157
pixel778    0.992157
pixel779    0.996078
pixel780    0.243137
pixel781    0.000000
pixel782    0.000000
pixel783    0.000000
pixel784    0.000000
dtype: float64

In [7]:
mnist.DESCR

"**Author**: Yann LeCun, Corinna Cortes, Christopher J.C. Burges  \n**Source**: [MNIST Website](http://yann.lecun.com/exdb/mnist/) - Date unknown  \n**Please cite**:  \n\nThe MNIST database of handwritten digits with 784 features, raw data available at: http://yann.lecun.com/exdb/mnist/. It can be split in a training set of the first 60,000 examples, and a test set of 10,000 examples  \n\nIt is a subset of a larger set available from NIST. The digits have been size-normalized and centered in a fixed-size image. It is a good database for people who want to try learning techniques and pattern recognition methods on real-world data while spending minimal efforts on preprocessing and formatting. The original black and white (bilevel) images from NIST were size normalized to fit in a 20x20 pixel box while preserving their aspect ratio. The resulting images contain grey levels as a result of the anti-aliasing technique used by the normalization algorithm. the images were centered in a 28x28 image by computing the center of mass of the pixels, and translating the image so as to position this point at the center of the 28x28 field.  \n\nWith some classification methods (particularly template-based methods, such as SVM and K-nearest neighbors), the error rate improves when the digits are centered by bounding box rather than center of mass. If you do this kind of pre-processing, you should report it in your publications. The MNIST database was constructed from NIST's NIST originally designated SD-3 as their training set and SD-1 as their test set. However, SD-3 is much cleaner and easier to recognize than SD-1. The reason for this can be found on the fact that SD-3 was collected among Census Bureau employees, while SD-1 was collected among high-school students. Drawing sensible conclusions from learning experiments requires that the result be independent of the choice of training set and test among the complete set of samples. Therefore it was necessary to build a new database by mixing NIST's datasets.  \n\nThe MNIST training set is composed of 30,000 patterns from SD-3 and 30,000 patterns from SD-1. Our test set was composed of 5,000 patterns from SD-3 and 5,000 patterns from SD-1. The 60,000 pattern training set contained examples from approximately 250 writers. We made sure that the sets of writers of the training set and test set were disjoint. SD-1 contains 58,527 digit images written by 500 different writers. In contrast to SD-3, where blocks of data from each writer appeared in sequence, the data in SD-1 is scrambled. Writer identities for SD-1 is available and we used this information to unscramble the writers. We then split SD-1 in two: characters written by the first 250 writers went into our new training set. The remaining 250 writers were placed in our test set. Thus we had two sets with nearly 30,000 examples each. The new training set was completed with enough examples from SD-3, starting at pattern # 0, to make a full set of 60,000 training patterns. Similarly, the new test set was completed with SD-3 examples starting at pattern # 35,000 to make a full set with 60,000 test patterns. Only a subset of 10,000 test images (5,000 from SD-1 and 5,000 from SD-3) is available on this site. The full 60,000 sample training set is available.\n\nDownloaded from openml.org."

In [8]:
mnist.target.head()

0    5
1    0
2    4
3    1
4    9
Name: class, dtype: category
Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']

In [9]:
mnist.target_names

['class']

In [10]:
mnist.target.astype(int)[0:10]

0    5
1    0
2    4
3    1
4    9
5    2
6    1
7    3
8    1
9    4
Name: class, dtype: int64

In [11]:
# One Hot Encoding using numpy eye
np.eye(10)[mnist.target.astype(int)[0:10]]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [12]:
help(pd.get_dummies)

Help on function get_dummies in module pandas.core.reshape.encoding:

get_dummies(data, prefix=None, prefix_sep: 'str | Iterable[str] | dict[str, str]' = '_', dummy_na: 'bool' = False, columns=None, sparse: 'bool' = False, drop_first: 'bool' = False, dtype: 'NpDtype | None' = None) -> 'DataFrame'
    Convert categorical variable into dummy/indicator variables.

    Each variable is converted in as many 0/1 variables as there are different
    values. Columns in the output are each named after a value; if the input is
    a DataFrame, the name of the original variable is prepended to the value.

    Parameters
    ----------
    data : array-like, Series, or DataFrame
        Data of which to get dummy indicators.
    prefix : str, list of str, or dict of str, default None
        String to append DataFrame column names.
        Pass a list with length equal to the number of columns
        when calling get_dummies on a DataFrame. Alternatively, `prefix`
        can be a dictionary mapping column names to prefixes.
    prefix_sep : str, default '_'
        If appending prefix, separator/delimiter to use. Or pass a
        list or dictionary as with `prefix`.
    dummy_na : bool, default False
        Add a column to indicate NaNs, if False NaNs are ignored.
    columns : list-like, default None
        Column names in the DataFrame to be encoded.
        If `columns` is None then all the columns with
        `object`, `string`, or `category` dtype will be converted.
    sparse : bool, default False
        Whether the dummy-encoded columns should be backed by
        a :class:`SparseArray` (True) or a regular NumPy array (False).
    drop_first : bool, default False
        Whether to get k-1 dummies out of k categorical levels by removing the
        first level.
    dtype : dtype, default bool
        Data type for new columns. Only a single dtype is allowed.

    Returns
    -------
    DataFrame
        Dummy-coded data. If `data` contains other columns than the
        dummy-coded one(s), these will be prepended, unaltered, to the result.

    See Also
    --------
    Series.str.get_dummies : Convert Series of strings to dummy codes.
    :func:`~pandas.from_dummies` : Convert dummy codes to categorical ``DataFrame``.

    Notes
    -----
    Reference :ref:`the user guide <reshaping.dummies>` for more examples.

    Examples
    --------
    >>> s = pd.Series(list('abca'))

    >>> pd.get_dummies(s)
           a      b      c
    0   True  False  False
    1  False   True  False
    2  False  False   True
    3   True  False  False

    >>> s1 = ['a', 'b', np.nan]

    >>> pd.get_dummies(s1)
           a      b
    0   True  False
    1  False   True
    2  False  False

    >>> pd.get_dummies(s1, dummy_na=True)
           a      b    NaN
    0   True  False  False
    1  False   True  False
    2  False  False   True

    >>> df = pd.DataFrame({'A': ['a', 'b', 'a'], 'B': ['b', 'a', 'c'],
    ...                    'C': [1, 2, 3]})

    >>> pd.get_dummies(df, prefix=['col1', 'col2'])
       C  col1_a  col1_b  col2_a  col2_b  col2_c
    0  1    True   False   False    True   False
    1  2   False    True    True   False   False
    2  3    True   False   False   False    True

    >>> pd.get_dummies(pd.Series(list('abcaa')))
           a      b      c
    0   True  False  False
    1  False   True  False
    2  False  False   True
    3   True  False  False
    4   True  False  False

    >>> pd.get_dummies(pd.Series(list('abcaa')), drop_first=True)
           b      c
    0  False  False
    1   True  False
    2  False   True
    3  False  False
    4  False  False

    >>> pd.get_dummies(pd.Series(list('abc')), dtype=float)
         a    b    c
    0  1.0  0.0  0.0
    1  0.0  1.0  0.0
    2  0.0  0.0  1.0

In [13]:
mnist_lables = np.eye(10)[mnist.target.astype('int')]
mnist_lables[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [14]:
train_images, test_images, train_lables, test_lables = train_test_split(
    mnist_images, mnist_lables, test_size=0.2, random_state=42)

In [15]:
train_images.head()

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
47339,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
67456,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12308,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32557,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
664,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
mnist_lables[:10]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [30]:
# Activation Function
def relu(ws):
  return np.maximum(0, ws)

def softmax(ws):
  exp_ws = np.exp(ws - np.max(ws, axis=-1, keepdims=True))
  return exp_ws / np.sum(exp_ws, axis=-1, keepdims=True)

In [31]:
# Layer
def dense_layer_neurons(input, weights, bias, activation='relu'):
  weighted_sum = np.dot(input, weights) + bias
  return relu(weighted_sum) if activation == 'relu' else softmax(weighted_sum)

In [32]:
# Hyperparameters

imput_size = 28*28  # number of pixels in the image
hidden_size = 128   # Can be anything
output_size = 10    # number of classes

batch_size = 64
learning_rate = 0.1
epochs = 10
steps = len(train_images) // batch_size

In [33]:
# Initialize Weights
weights_input_hidden = np.random.randn(imput_size, hidden_size) * 0.01
bias_input_hidden = np.zeros((1, hidden_size))

weights_hidden_output = np.random.randn(hidden_size, output_size) * 0.01
bias_hidden_output = np.zeros((1, output_size))

weights_hidden_output = np.random.randn(hidden_size, output_size) * 0.01
bias_hidden_output = np.zeros((1, output_size))

In [34]:
weights_input_hidden

array([[ 0.00161053, -0.01562025,  0.00843656, ...,  0.000596  ,
         0.01156508,  0.01465768],
       [ 0.00469335, -0.00431951, -0.00308017, ...,  0.00313693,
        -0.00061329, -0.0007924 ],
       [-0.00624844,  0.00791314,  0.00169346, ...,  0.01168332,
        -0.01517422, -0.00094519],
       ...,
       [-0.0159406 , -0.01082431, -0.00677586, ..., -0.01207957,
        -0.01470284,  0.00257158],
       [ 0.01016727, -0.00766598,  0.00506439, ..., -0.01285717,
         0.00112467, -0.00686997],
       [ 0.00232507,  0.01536693,  0.01533508, ...,  0.00087187,
         0.00610735,  0.00115781]])

In [35]:
bias_input_hidden

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [36]:
weights_input_hidden.shape

(784, 128)

In [37]:
bias_input_hidden.shape

(1, 128)

In [38]:
# Total number of parameters
784*128 + 784 + 128*10 + 10

102426

In [41]:
# The Training Loop

for epoch in range(epochs):
  for step in range(steps):
    start_idx = step * batch_size
    end_idx = (step + 1) * batch_size

    # Forward Pass
    input_data = train_images[start_idx:end_idx]
    hidden_layer = dense_layer_neurons(input_data, weights_input_hidden, bias_input_hidden, activation='relu')
    output_layer = dense_layer_neurons(hidden_layer, weights_hidden_output, bias_hidden_output, activation='softmax')

    # Compute Loss - categorical crossentropy
    loss = -np.sum(train_lables[start_idx:end_idx] * np.log(output_layer + 1e-8)) / batch_size

    # Backward Pass (Gradient Descent)
    delta = output_layer - train_lables[start_idx:end_idx]
    gred_hidden = np.dot(delta, weights_hidden_output.T) * (hidden_layer > 0)  # Differenciation using matrix multiplication

    # Update weights and baises
    weights_hidden_output = weights_hidden_output - learning_rate * np.dot(hidden_layer.T, delta) / batch_size
    bias_hidden_output = bias_hidden_output - learning_rate * np.sum(delta, axis=0, keepdims=True) / batch_size

    weights_input_hidden = weights_input_hidden - learning_rate * np.dot(input_data.T, gred_hidden) / batch_size
    bias_input_hidden = bias_input_hidden - learning_rate * np.sum(gred_hidden, axis=0, keepdims=True) / batch_size

  # Compute Accuracy on validation set
  hidden_layer_val = dense_layer_neurons(test_images, weights_input_hidden, bias_input_hidden)
  output_layer_val = dense_layer_neurons(hidden_layer_val, weights_hidden_output, bias_hidden_output, activation='softmax')
  predictions = np.argmax(output_layer_val, axis=1)
  true_labels = np.argmax(test_lables, axis=1)
  accuracy = np.mean(predictions == np.argmax(test_lables, axis=1))

  print(f'Epoch {epoch + 1}/{epochs}, Loss: {loss:.4f}, Accuracy: {accuracy:.4f}')

Epoch 1/10, Loss: 0.0934, Accuracy: 0.9656
Epoch 2/10, Loss: 0.0885, Accuracy: 0.9679
Epoch 3/10, Loss: 0.0853, Accuracy: 0.9696
Epoch 4/10, Loss: 0.0795, Accuracy: 0.9703
Epoch 5/10, Loss: 0.0746, Accuracy: 0.9714
Epoch 6/10, Loss: 0.0724, Accuracy: 0.9719
Epoch 7/10, Loss: 0.0685, Accuracy: 0.9722
Epoch 8/10, Loss: 0.0645, Accuracy: 0.9729
Epoch 9/10, Loss: 0.0596, Accuracy: 0.9731
Epoch 10/10, Loss: 0.0546, Accuracy: 0.9729